# SITE CONFIGURATION
baseurl: "/Sportstechwest"
url: ""

# THEME-SPECIFIC CONFIGURATION
title: SportsTechWest                                   # site's title
description: "Rashad West's basketball project is transforming the way youth engage with STEAM (Science, Technology, Engineering, Arts, Mathematics) education. What began as an initiative to teach mathematics through basketball has now evolved into two dynamic platforms: a robot sports coding game for younger kids and an analytics platform designed specifically for NIL athletes. By integrating basketball drills with math concepts like scoring and probability, the program offers students an interactive and practical approach to learning, using the game they love as a tool for academic growth."
avatar: assets/img/logo/logo.png                        # Empty for no avatar in navbar
favicon: assets/img/logo/favicon.png                           # Icon displayed in the tab

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Measurement ID, e.g. "G-00000"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments options
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post" # Use your specific layout name here
