#!/bin/bash

# Manual setup instructions for Raspberry Pi
# Use this if SSH password isn't working

echo "📋 MANUAL SETUP INSTRUCTIONS FOR RASPBERRY PI"
echo "=============================================="
echo ""
echo "Since SSH password isn't working, do this manually:"
echo ""
echo "Step 1: SSH into Pi (try password one more time)"
echo "  ssh pi@192.168.1.226"
echo ""
echo "Step 2: Once on Pi, run these commands:"
echo ""
echo "  # Create .env file"
echo "  cat > ~/.n8n/.env << 'ENVEOF'"
echo "  UNITY_REPO_URL=https://github.com/rashadwest/BallCode.git"
echo "  UNITY_PROJECT_PATH=/Users/rashadwest/BTEBallCODE"
echo "  WORKFLOW_PATH=/Users/rashadwest/Sportstechwest/workflows/BallCODE-Book"
echo "  ENVEOF"
echo ""
echo "  # Verify it was created"
echo "  cat ~/.n8n/.env"
echo ""
echo "  # Restart n8n"
echo "  sudo systemctl restart n8n"
echo ""
echo "  # Check n8n status"
echo "  sudo systemctl status n8n"
echo ""
echo "Step 3: Exit Pi"
echo "  exit"
echo ""
echo "Step 4: Test from Mac"
echo "  curl http://192.168.1.226:5678/healthz"
echo ""
echo "=============================================="
echo ""
echo "Or, set up SSH keys first (recommended):"
echo ""
echo "  1. Generate key: ssh-keygen"
echo "  2. Copy to Pi: ssh-copy-id pi@192.168.1.226"
echo "  3. Then you can automate everything!"
echo ""



