#!/bin/bash
# Quick reference for setting n8n environment variables
# Note: n8n doesn't have a public API for env vars, so these are manual steps

echo "=========================================="
echo "n8n Environment Variables Setup Guide"
echo "=========================================="
echo ""
echo "⚠️  n8n does NOT have a public API for setting environment variables."
echo "You must set them in the n8n UI."
echo ""
echo "Steps:"
echo "1. Go to: http://192.168.1.226:5678"
echo "2. Click Settings (gear icon, top right)"
echo "3. Click Environment Variables"
echo "4. Add each variable:"
echo ""
echo "   Variable 1: GITHUB_PAT"
echo "   Value: [your GitHub token]"
echo ""
echo "   Variable 2: NETLIFY_AUTH_TOKEN"
echo "   Value: [your Netlify token]"
echo ""
echo "   Variable 3: NETLIFY_SITE_ID"
echo "   Value: [your Netlify site ID]"
echo ""
echo "5. Click Save for each"
echo ""
echo "To verify variables are set:"
echo "  python scripts/verify-garvis-unity-integration.py"
echo ""
