#!/bin/bash
# Python Hybrid n8n Workflow - Environment Setup Script
# Automatically configures environment for hybrid workflow

# Copyright © 2025 Rashad West. All Rights Reserved.

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🐍 Python Hybrid n8n Workflow - Environment Setup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Get script directory (where this script is located)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKFLOW_PATH="$SCRIPT_DIR"

echo -e "${BLUE}📁 Detected Workflow Path:${NC} $WORKFLOW_PATH"
echo ""

# Check Python scripts exist
echo -e "${BLUE}🔍 Checking Python Scripts...${NC}"
MISSING_SCRIPTS=0

if [ ! -f "$WORKFLOW_PATH/scripts/n8n-check-github.py" ]; then
    echo -e "${RED}❌ Missing: scripts/n8n-check-github.py${NC}"
    MISSING_SCRIPTS=1
else
    echo -e "${GREEN}✅ Found: scripts/n8n-check-github.py${NC}"
fi

if [ ! -f "$WORKFLOW_PATH/scripts/n8n-check-netlify.py" ]; then
    echo -e "${RED}❌ Missing: scripts/n8n-check-netlify.py${NC}"
    MISSING_SCRIPTS=1
else
    echo -e "${GREEN}✅ Found: scripts/n8n-check-netlify.py${NC}"
fi

if [ ! -f "$WORKFLOW_PATH/scripts/monitor-builds.py" ]; then
    echo -e "${RED}❌ Missing: scripts/monitor-builds.py${NC}"
    MISSING_SCRIPTS=1
else
    echo -e "${GREEN}✅ Found: scripts/monitor-builds.py${NC}"
fi

if [ $MISSING_SCRIPTS -eq 1 ]; then
    echo ""
    echo -e "${RED}❌ Missing required Python scripts. Please ensure all scripts are present.${NC}"
    exit 1
fi

echo ""

# Make scripts executable
echo -e "${BLUE}🔧 Making Scripts Executable...${NC}"
chmod +x "$WORKFLOW_PATH/scripts/n8n-check-github.py" 2>/dev/null || true
chmod +x "$WORKFLOW_PATH/scripts/n8n-check-netlify.py" 2>/dev/null || true
echo -e "${GREEN}✅ Scripts are executable${NC}"
echo ""

# Check Python dependencies
echo -e "${BLUE}🐍 Checking Python Dependencies...${NC}"
if ! python3 -c "import requests" 2>/dev/null; then
    echo -e "${YELLOW}⚠️  'requests' module not found. Installing...${NC}"
    pip3 install requests 2>/dev/null || {
        echo -e "${RED}❌ Failed to install 'requests'. Please install manually:${NC}"
        echo "   pip3 install requests"
        exit 1
    }
    echo -e "${GREEN}✅ 'requests' installed${NC}"
else
    echo -e "${GREEN}✅ Python dependencies OK${NC}"
fi
echo ""

# Test Python scripts (without credentials, should return error JSON)
echo -e "${BLUE}🧪 Testing Python Scripts...${NC}"
if python3 "$WORKFLOW_PATH/scripts/n8n-check-github.py" 2>&1 | grep -q '"status"'; then
    echo -e "${GREEN}✅ n8n-check-github.py outputs valid JSON${NC}"
else
    echo -e "${YELLOW}⚠️  n8n-check-github.py test inconclusive (credentials may be missing)${NC}"
fi

if python3 "$WORKFLOW_PATH/scripts/n8n-check-netlify.py" 2>&1 | grep -q '"status"'; then
    echo -e "${GREEN}✅ n8n-check-netlify.py outputs valid JSON${NC}"
else
    echo -e "${YELLOW}⚠️  n8n-check-netlify.py test inconclusive (credentials may be missing)${NC}"
fi
echo ""

# Create/update .n8n-hybrid-env file
ENV_FILE="$WORKFLOW_PATH/.n8n-hybrid-env"
echo -e "${BLUE}📝 Creating Environment Configuration...${NC}"

cat > "$ENV_FILE" << EOF
# Python Hybrid n8n Workflow - Environment Configuration
# Generated by setup-python-hybrid-env.sh
# Copyright © 2025 Rashad West. All Rights Reserved.

# REQUIRED: Path to workflow directory (used by Python scripts)
export WORKFLOW_PATH="$WORKFLOW_PATH"

# REQUIRED: GitHub API Configuration
# Get token from: https://github.com/settings/tokens
export GITHUB_TOKEN=""
export GITHUB_REPO_OWNER=""
export GITHUB_REPO_NAME=""
export GITHUB_WORKFLOW_FILE=""

# REQUIRED: Netlify API Configuration
# Get token from: https://app.netlify.com/user/applications
export NETLIFY_AUTH_TOKEN=""
export NETLIFY_SITE_ID=""

# OPTIONAL: n8n Instance Configuration
# Set to 'dev' for local Mac, 'prod' for Raspberry Pi
export N8N_INSTANCE_ROLE="dev"

# OPTIONAL: Override scheduled builds on dev
# Set to '1' to allow scheduled builds on dev instance
export ALLOW_SCHEDULED_BUILDS="0"

# OPTIONAL: Netlify Site Name (for URL generation)
export NETLIFY_SITE_NAME="ballcode-game"
EOF

echo -e "${GREEN}✅ Created: .n8n-hybrid-env${NC}"
echo ""

# Display n8n configuration instructions
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}📋 n8n Environment Variables to Set${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Go to n8n UI → Settings → Environment Variables${NC}"
echo ""
echo -e "${GREEN}REQUIRED Variables:${NC}"
echo "  WORKFLOW_PATH=$WORKFLOW_PATH"
echo "  GITHUB_TOKEN=<your_github_token>"
echo "  GITHUB_REPO_OWNER=<your_owner>"
echo "  GITHUB_REPO_NAME=<your_repo>"
echo "  GITHUB_WORKFLOW_FILE=<your_workflow_file.yml>"
echo "  NETLIFY_AUTH_TOKEN=<your_netlify_token>"
echo "  NETLIFY_SITE_ID=<your_site_id>"
echo ""
echo -e "${GREEN}OPTIONAL Variables:${NC}"
echo "  N8N_INSTANCE_ROLE=dev  # or 'prod' for Raspberry Pi"
echo "  ALLOW_SCHEDULED_BUILDS=0  # set to '1' to allow on dev"
echo "  NETLIFY_SITE_NAME=ballcode-game"
echo ""

# Check if workflow JSON exists on desktop
DESKTOP_WORKFLOW="/Users/rashadwest/Desktop/n8n-unity-build-orchestrator-PYTHON-HYBRID.json"
if [ -f "$DESKTOP_WORKFLOW" ]; then
    echo -e "${GREEN}✅ Found workflow JSON on desktop${NC}"
    echo ""
    echo -e "${BLUE}📋 Next Steps:${NC}"
    echo "  1. Validate workflow: python3 scripts/validate-hybrid-workflow.py $DESKTOP_WORKFLOW"
    echo "  2. Import to n8n: Workflows → Import from File → Select desktop file"
    echo "  3. Set environment variables in n8n (see above)"
    echo "  4. Test workflow with webhook trigger"
else
    echo -e "${YELLOW}⚠️  Workflow JSON not found on desktop${NC}"
    echo "  Expected: $DESKTOP_WORKFLOW"
    echo ""
    echo -e "${BLUE}📋 Next Steps:${NC}"
    echo "  1. Ensure workflow JSON is on desktop"
    echo "  2. Validate workflow: python3 scripts/validate-hybrid-workflow.py <path>"
    echo "  3. Import to n8n"
fi
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}📚 Documentation:${NC} PYTHON-HYBRID-QUICK-START.md"
echo ""


