#!/usr/bin/env python3
"""
Analyze Execution Errors
Helps identify what's causing workflow failures

Copyright © 2025 Rashad West. All Rights Reserved.
"""

import sys

def main():
    """Guide user to analyze execution errors."""
    print("=" * 70)
    print("🔍 How to Analyze Execution Errors in n8n")
    print("=" * 70)
    print()
    print("Based on your execution log, here are the failing executions:")
    print()
    print("❌ Screenshot-to-Fix Errors:")
    print("   - Exec ID 85: Error (453ms) - 15:13:40")
    print("   - Exec ID 82: Error (1.035s) - 15:12:44")
    print("   - Exec ID 80: Error (504ms) - 15:08:14")
    print()
    print("❌ Unity Build Orchestrator Error:")
    print("   - Exec ID 79: Error (84ms) - 15:08:14")
    print()
    print("✅ But also successes:")
    print("   - Exec 84: Full Integration - Success (40.427s)")
    print("   - Exec 83: Unity Build Orchestrator - Success (75ms)")
    print("   - Exec 81: Unity Build Orchestrator - Success (79ms)")
    print()
    print("=" * 70)
    print("📋 Step-by-Step Error Analysis")
    print("=" * 70)
    print()
    print("For EACH failed execution, do this:")
    print()
    print("1. Click on the execution (e.g., Exec ID 85)")
    print()
    print("2. Look at the workflow diagram:")
    print("   - Green nodes = worked")
    print("   - Red nodes = failed (THIS IS THE PROBLEM)")
    print("   - Yellow nodes = warnings")
    print()
    print("3. Click on the RED node:")
    print("   - Read the error message")
    print("   - Check the error type")
    print("   - Note which node failed")
    print()
    print("4. Common error patterns:")
    print()
    print("   For Screenshot-to-Fix (Exec 85, 82, 80):")
    print("   - Likely: OpenAI credential issue")
    print("   - Or: 'Message a model' node configuration")
    print("   - Or: Input data format issue")
    print()
    print("   For Unity Build Orchestrator (Exec 79):")
    print("   - Likely: Environment variable missing")
    print("   - Or: First Code node error")
    print("   - Or: Validation error")
    print()
    print("=" * 70)
    print("🔧 Quick Fixes Based on Error Type")
    print("=" * 70)
    print()
    print("If error is 'Credential not found' or 'OpenAI API key missing':")
    print("  → Add OpenAI credential in n8n Credentials")
    print("  → Assign to 'Message a model' node")
    print()
    print("If error is 'environment variable is not set':")
    print("  → Add env vars in Settings → Environment Variables")
    print("  → Restart n8n")
    print()
    print("If error is 'Cannot read property' or 'TypeError':")
    print("  → Check Code node for null/undefined access")
    print("  → Add null checks")
    print()
    print("If error is 'Invalid input' or 'Missing required field':")
    print("  → Check input data format")
    print("  → Verify previous nodes output correct data")
    print()
    print("=" * 70)
    print("📊 Pattern Analysis")
    print("=" * 70)
    print()
    print("Screenshot-to-Fix: 3 failures (consistent)")
    print("  → Likely: Same error repeating")
    print("  → Check Exec 85 (most recent) for exact error")
    print()
    print("Unity Build Orchestrator: 1 failure, 2 successes (intermittent)")
    print("  → Likely: Environment variable issue (sometimes set, sometimes not)")
    print("  → Or: Conditional logic issue")
    print("  → Check Exec 79 for exact error")
    print()
    print("Full Integration: 1 success")
    print("  → Working! ✅")
    print()
    print("=" * 70)
    print("💡 Next Steps")
    print("=" * 70)
    print()
    print("1. Check Exec 85 (Screenshot-to-Fix - most recent):")
    print("   - Click on it in n8n")
    print("   - Find red node")
    print("   - Copy error message")
    print()
    print("2. Check Exec 79 (Unity Build Orchestrator):")
    print("   - Click on it in n8n")
    print("   - Find red node")
    print("   - Copy error message")
    print()
    print("3. Share the error messages with me")
    print("   - I'll provide exact fixes")
    print()
    print("4. Or fix based on common patterns above")
    print()

if __name__ == "__main__":
    main()

