#!/usr/bin/env python3
"""
Automated n8n Environment Variables Setup
Sets all required environment variables automatically

Copyright © 2025 Rashad West. All Rights Reserved.
"""

import os
import sys
from pathlib import Path

# Required environment variables for all workflows
REQUIRED_ENV_VARS = {
    "GITHUB_REPO_OWNER": "rashadwest",
    "GITHUB_REPO_NAME": "BTEBallCODE",
    "GITHUB_WORKFLOW_FILE": "unity-webgl-build.yml",
    "NETLIFY_SITE_ID": "",  # Will prompt if not set
    "NETLIFY_SITE_NAME": "ballcode-game",
    "N8N_INSTANCE_ROLE": "prod",
    "WORKFLOW_PATH": "/Users/rashadwest/Sportstechwest/workflows/BallCODE-Book"
}

def create_env_file():
    """Create .env file for n8n."""
    env_file = Path(__file__).parent.parent / ".env.n8n"
    
    print("=" * 70)
    print("🤖 Automated n8n Environment Variables Setup")
    print("=" * 70)
    print()
    
    # Check existing .env file
    existing_vars = {}
    if env_file.exists():
        print(f"📄 Found existing .env file: {env_file}")
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_vars[key] = value
        print(f"   Found {len(existing_vars)} existing variables")
        print()
    
    # Build environment variables
    env_vars = {}
    
    for key, default_value in REQUIRED_ENV_VARS.items():
        if key in existing_vars:
            env_vars[key] = existing_vars[key]
            print(f"✅ {key} = {existing_vars[key]} (from existing)")
        elif default_value:
            env_vars[key] = default_value
            print(f"✅ {key} = {default_value} (using default)")
        else:
            # Prompt for missing values
            value = input(f"❓ {key} (required): ").strip()
            if value:
                env_vars[key] = value
                print(f"✅ {key} = {value}")
            else:
                print(f"⚠️  {key} not set - may cause issues")
                env_vars[key] = ""
    
    # Write .env file
    print()
    print("📝 Writing .env file...")
    
    with open(env_file, 'w') as f:
        f.write("# n8n Environment Variables\n")
        f.write("# Auto-generated by auto-setup-n8n-env-vars.py\n")
        f.write("# Date: " + str(Path(__file__).stat().st_mtime) + "\n\n")
        
        for key, value in sorted(env_vars.items()):
            f.write(f"{key}={value}\n")
    
    print(f"✅ Saved to: {env_file}")
    print()
    
    return env_vars, env_file

def create_n8n_setup_script(env_vars, env_file):
    """Create script to set variables in n8n."""
    script_file = Path(__file__).parent / "setup-n8n-env-vars.sh"
    
    print("📝 Creating n8n setup script...")
    
    script_content = f"""#!/bin/bash
# Automated n8n Environment Variables Setup Script
# Generated by auto-setup-n8n-env-vars.py

echo "🤖 Setting up n8n environment variables..."
echo ""

# Check if n8n is running on Pi
N8N_HOST="192.168.1.226"
N8N_PORT="5678"

echo "📡 Checking n8n connectivity..."
if ! curl -s http://$N8N_HOST:$N8N_PORT/healthz > /dev/null; then
    echo "❌ Cannot connect to n8n at http://$N8N_HOST:$N8N_PORT"
    echo "   Make sure n8n is running"
    exit 1
fi

echo "✅ n8n is accessible"
echo ""

# Note: n8n environment variables need to be set in n8n Settings UI
# or in the system environment where n8n runs

echo "📋 Environment variables to set in n8n:"
echo ""
"""
    
    for key, value in sorted(env_vars.items()):
        script_content += f'echo "  {key}={value}"\n'
    
    script_content += f"""
echo ""
echo "🔧 To set these in n8n:"
echo "   1. Open: http://$N8N_HOST:$N8N_PORT"
echo "   2. Go to Settings → Environment Variables"
echo "   3. Add each variable above"
echo "   4. Restart n8n: sudo systemctl restart n8n"
echo ""
echo "💡 Or set them in n8n's system environment:"
echo "   SSH to Pi and add to /etc/systemd/system/n8n.service"
echo "   or ~/.n8n/.env file"
echo ""
echo "✅ Setup script created: {script_file}"
"""
    
    with open(script_file, 'w') as f:
        f.write(script_content)
    
    os.chmod(script_file, 0o755)
    
    print(f"✅ Created: {script_file}")
    print()
    
    return script_file

def create_comprehensive_test():
    """Create comprehensive test suite."""
    test_file = Path(__file__).parent / "comprehensive-n8n-test.py"
    
    print("📝 Creating comprehensive test suite...")
    
    test_content = '''#!/usr/bin/env python3
"""
Comprehensive n8n Test Suite
Tests all workflows, environment variables, credentials, and connectivity

Copyright © 2025 Rashad West. All Rights Reserved.
"""

import requests
import json
import sys
from pathlib import Path
from datetime import datetime

N8N_URL = "http://192.168.1.226:5678"

def test_n8n_connectivity():
    """Test if n8n is accessible."""
    print("🔍 Testing n8n connectivity...")
    try:
        response = requests.get(f"{N8N_URL}/healthz", timeout=5)
        if response.status_code == 200:
            print("   ✅ n8n is accessible")
            return True
        else:
            print(f"   ❌ n8n returned {response.status_code}")
            return False
    except Exception as e:
        print(f"   ❌ Cannot connect: {e}")
        return False

def test_workflow_webhooks():
    """Test all workflow webhooks."""
    print("\\n🧪 Testing workflow webhooks...")
    
    workflows = {
        "unity-build": {
            "webhook": "/webhook/unity-build",
            "payload": {"request": "Test", "branch": "main"}
        },
        "full-integration": {
            "webhook": "/webhook/full-integration",
            "payload": {"prompt": "Test"}
        },
        "screenshot-fix": {
            "webhook": "/webhook/screenshot-fix",
            "payload": {"screenshotUrl": "https://example.com/test.png", "context": "Test"}
        }
    }
    
    results = {}
    for name, config in workflows.items():
        try:
            response = requests.post(
                f"{N8N_URL}{config['webhook']}",
                json=config["payload"],
                timeout=30
            )
            results[name] = {
                "status_code": response.status_code,
                "success": response.status_code == 200,
                "response": response.text[:200] if response.text else ""
            }
            status = "✅" if response.status_code == 200 else "❌"
            print(f"   {status} {name}: {response.status_code}")
        except Exception as e:
            results[name] = {"success": False, "error": str(e)}
            print(f"   ❌ {name}: {e}")
    
    return results

def check_executions():
    """Check recent executions for errors."""
    print("\\n📊 Checking recent executions...")
    print("   (Check n8n UI: Executions tab for details)")
    return True

def main():
    """Run comprehensive tests."""
    print("=" * 70)
    print("🧪 Comprehensive n8n Test Suite")
    print("=" * 70)
    print()
    
    all_passed = True
    
    # Test connectivity
    if not test_n8n_connectivity():
        print("\\n❌ Cannot connect to n8n. Fix connectivity first.")
        return False
    
    # Test webhooks
    webhook_results = test_workflow_webhooks()
    
    # Check executions
    check_executions()
    
    # Summary
    print("\\n" + "=" * 70)
    print("📊 Test Summary")
    print("=" * 70)
    
    successful = sum(1 for r in webhook_results.values() if r.get("success"))
    total = len(webhook_results)
    
    print(f"\\nWebhook Tests: {successful}/{total} successful")
    
    if successful == total:
        print("\\n✅ All tests passed!")
        return True
    else:
        print("\\n⚠️  Some tests failed. Check n8n Executions tab for details.")
        return False

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
'''
    
    with open(test_file, 'w') as f:
        f.write(test_content)
    
    os.chmod(test_file, 0o755)
    
    print(f"✅ Created: {test_file}")
    print()
    
    return test_file

def main():
    """Main setup function."""
    # Create .env file
    env_vars, env_file = create_env_file()
    
    # Create setup script
    script_file = create_n8n_setup_script(env_vars, env_file)
    
    # Create comprehensive test
    test_file = create_comprehensive_test()
    
    print("=" * 70)
    print("✅ Automated Setup Complete!")
    print("=" * 70)
    print()
    print("📋 Next Steps:")
    print()
    print("1. Set environment variables in n8n:")
    print(f"   - Run: bash {script_file}")
    print("   - Or manually: Settings → Environment Variables")
    print()
    print("2. Restart n8n:")
    print("   ssh pi@192.168.1.226")
    print("   sudo systemctl restart n8n")
    print()
    print("3. Run comprehensive tests:")
    print(f"   python3 {test_file}")
    print()
    print("4. Check results and fix any remaining issues")
    print()

if __name__ == "__main__":
    main()


