#!/bin/bash
# Quick Manual Deploy Instructions
# Shows user exactly what to do for manual deployment

echo "============================================================"
echo "  QUICK MANUAL DEPLOYMENT - IF SCRIPT IS STUCK"
echo "============================================================"
echo ""
echo "📋 STEP-BY-STEP:"
echo ""
echo "1. Open Netlify Dashboard:"
echo "   https://app.netlify.com/sites/ballcode/deploys"
echo ""
echo "2. Click 'Deploy manually' or find the drag-and-drop area"
echo ""
echo "3. Drag this folder:"
echo "   /Users/rashadwest/BTEBallCODE/Builds/WebGL"
echo ""
echo "4. Click 'Deploy site'"
echo ""
echo "5. Wait 1-2 minutes → Game goes live!"
echo ""
echo "============================================================"
echo "  BUILD LOCATION"
echo "============================================================"
echo ""
echo "✅ Build ready at:"
echo "   /Users/rashadwest/BTEBallCODE/Builds/WebGL"
echo ""
BUILD_SIZE=$(du -sh /Users/rashadwest/BTEBallCODE/Builds/WebGL 2>/dev/null | cut -f1)
echo "📦 Build size: $BUILD_SIZE"
echo ""
echo "============================================================"
echo "  ALTERNATIVE: DIRECT NPX COMMAND"
echo "============================================================"
echo ""
echo "If you want to try direct command:"
echo ""
echo "cd /Users/rashadwest/BTEBallCODE"
echo "npx netlify-cli deploy --prod --dir Builds/WebGL --site 39ebfb47-c716-4f38-8f8b-7bfba36f3dc7"
echo ""
echo "============================================================"

