#!/bin/bash
# Unity Cloud Build Setup Checklist
# Interactive guide for setting up Unity Cloud Build

echo "============================================================"
echo "  Unity Cloud Build Setup Checklist"
echo "============================================================"

echo ""
echo "📋 Setup Steps:"
echo ""
echo "✅ Step 1: Sign In to Unity"
echo "   - I opened Unity ID page"
echo "   - Sign in with your Unity account"
echo "   - [ ] Signed in"
echo ""
echo "✅ Step 2: Access Cloud Build"
echo "   - I opened Unity Cloud Build page"
echo "   - Navigate to Cloud Build dashboard"
echo "   - [ ] Cloud Build dashboard open"
echo ""
echo "✅ Step 3: Connect GitHub Repository"
echo "   - Click 'New Project' or 'Add Project'"
echo "   - Select 'Connect Repository'"
echo "   - Authorize Unity to access GitHub"
echo "   - Select: rashadwest/BTEBallCODE"
echo "   - [ ] Repository connected"
echo ""
echo "✅ Step 4: Configure Build"
echo "   - Platform: WebGL"
echo "   - Unity Version: 2021.3.45f2 (or closest)"
echo "   - Build Name: BallCODE-WebGL"
echo "   - Build Target: WebGL"
echo "   - [ ] Build configured"
echo ""
echo "✅ Step 5: Set Up Deployment (Optional)"
echo "   - Add Netlify deployment (if desired)"
echo "   - OR download build manually"
echo "   - [ ] Deployment configured (or skipped)"
echo ""
echo "✅ Step 6: Test Build"
echo "   - Click 'Build Now' or push to GitHub"
echo "   - Monitor build progress"
echo "   - Verify build succeeds"
echo "   - [ ] Build successful"
echo ""
echo "📋 What You Need:"
echo "   - Unity ID account (same as Unity Hub)"
echo "   - GitHub repository access"
echo "   - Netlify credentials (if auto-deploying)"
echo ""
echo "✅ Setup complete when all steps are checked!"
echo ""


